require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '\#.*' # ignore long comments

Metrics/BlockLength:
  Exclude: ['**/*_spec.rb']

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
