require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['\#.*'] # ignore long comments

Metrics/BlockLength:
  Exclude: ['**/*_spec.rb']

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'shared_context']

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

RSpec/EmptyExampleGroup:
  CustomIncludeMethods:
    - 'its_block'

RSpec/ImplicitSubject:
  Enabled: false
